[Interface]
PrivateKey = EIB++43eB9Lh2XjIHDcNRsgMB594rpH5TydqNHuhMlg=
Address = 10.66.66.2/32
DNS = 1.1.1.1, 8.8.8.8
MTU = 1280

[Peer]
PublicKey = YXPh69MlXcC6xvGXpOhWHQm570js0y+8ihnjJv8XHWg=
AllowedIPs = 0.0.0.0/0
Endpoint = 193.233.211.41:51820
PersistentKeepalive = 25
Jc = 4
Jmin = 40
Jmax = 70
S1 = 0
S2 = 0
H1 = 1
H2 = 2
H3 = 3
H4 = 4
